language: ruby
bundler_args: --without dev
script: bundle exec rake ci
rvm: []  # only run the builds in the matrix below
matrix:
  include:
    - rvm: 1.9.3
      env: DB_NAZI_ADAPTER=sqlite3
    - rvm: 1.9.3
      env: DB_NAZI_ADAPTER=mysql
    - rvm: 1.9.3
      env: DB_NAZI_ADAPTER=mysql2
    - rvm: 1.9.3
      before_script: psql -c 'create database myapp_test;' -U postgres
      env: DB_NAZI_ADAPTER=postgresql

    - rvm: 2.1.0
      env: DB_NAZI_ADAPTER=sqlite3
    - rvm: 2.1.0
      env: DB_NAZI_ADAPTER=mysql
    - rvm: 2.1.0
      env: DB_NAZI_ADAPTER=mysql2
    - rvm: 2.1.0
      before_script: psql -c 'create database myapp_test;' -U postgres
      env: DB_NAZI_ADAPTER=postgresql

    - rvm: rbx-2
      env: DB_NAZI_ADAPTER=sqlite3
    - rvm: rbx-2
      env: DB_NAZI_ADAPTER=mysql
    - rvm: rbx-2
      env: DB_NAZI_ADAPTER=mysql2
    - rvm: rbx-2
      before_script: psql -c 'create database myapp_test;' -U postgres
      env: DB_NAZI_ADAPTER=postgresql

    - rvm: jruby-19mode
      env: DB_NAZI_ADAPTER=jdbcmysql
